version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=stats-db
      - POSTGRES_PORT=5432
      - TZ=Europe/Moscow
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ewm" ]
      interval: 5s
      timeout: 5s
      retries: 5

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=ewm-db
      - POSTGRES_PORT=5432
      - TZ=Europe/Moscow
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ewm" ]
      interval: 5s
      timeout: 5s
      retries: 5

  stats-server:
    build: ./stats/stats-server
    image: stats-server-dock
    container_name: stats-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      stats-db:
        condition: service_healthy
      ewm-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASS=admin

  ewm-service:
    build: ./main-service
    image: ewm-service-dock
    container_name: ewm-service
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      stats-db:
        condition: service_healthy
      ewm-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASS=admin