drop table if exists hits;

create table if not exists hits(
    hit_id bigint generated by default as identity not null primary key,
    app varchar(128) not null,
    uri varchar(1024) not null,
    ip varchar(64) not null,
    hit_created timestamp
);